name: Naukri Auto Update (Windows)

on:
  workflow_dispatch:

jobs:
  run-naukri:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Google Chrome
        run: |
          choco install googlechrome --no-progress --yes
          echo "Refreshing environment..."
          refreshenv
          # Verify Chrome installation
          & "C:\Program Files\Google\Chrome\Application\chrome.exe" --version

      - name: Run Naukri automation
        env:
          USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          MOBILE: ${{ secrets.NAUKRI_MOBILE }}
        run: |
          echo "Running Naukri script..."
          python naukri.py
